<?php

class BlocksTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('blocks')->delete();
        
		\DB::table('blocks')->insert(array (
			0 => 
			array (
				'id' => '1',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'header',
				'layout' => 'default',
				'name' => 'menu_select_block',
				'title' => 'anastasia::strings.menu',
				'tpl' => 'anastasia::blocks/topmenu',
				'params' => 'czoxOiI5Ijs=',
				'order_weight' => '0',
				'created_at' => '2015-04-18 09:46:43',
				'updated_at' => '2015-04-19 07:41:01',
			),
			1 => 
			array (
				'id' => '2',
				'theme_domain' => 'anastasia',
				'position' => '3',
				'grid' => 'body',
				'layout' => 'default',
				'name' => 'html_box',
				'title' => 'anastasia::strings.html_box',
				'tpl' => 'anastasia::blocks/htmlbox',
				'params' => 'YTo0OntzOjU6InRpdGxlIjtzOjE1OiJXaGF0IHRvIGRvIG5vdz8iO3M6NDoidGV4dCI7czoyMzA6IjxwPllvdSBjYW4gZ28gYW5kIHJlLWFycmFuZ2UgdGhlIGJsb2NrcyBvZiB5b3VyIHNpdGUgdGhyb3VnaCB0aGUgQmxvY2sgTWFuYWdlciBpbiB0aGUgYWRtaW4gYXJlYS48L3A+DQo8cD5CbG9ja3MgYXJlIGNvbnRlbnQgaXRlbXMgbGlrZSB0aGlzIG9uZSB0aGF0IGNhbiBiZSBhZGRlZCB0byBzcGVjaWZpZWQgZ3JpZCBwb3NpdGlvbnMgdGhlIHRoZW1lIHNwZWNpZmllcy48L3A+DQo8cD4mbmJzcDs8L3A+IjtzOjM6InVybCI7czoyMToiL2JhY2tlbmQvYmxvY2ttYW5hZ2VyIjtzOjY6ImJ1dHRvbiI7czoxOToiR28gdG8gYmxvY2sgbWFuYWdlciI7fQ==',
				'order_weight' => '0',
				'created_at' => '2015-04-19 11:54:18',
				'updated_at' => '2015-04-29 04:31:49',
			),
			2 => 
			array (
				'id' => '3',
				'theme_domain' => 'anastasia',
				'position' => '4',
				'grid' => 'body',
				'layout' => 'default',
				'name' => 'html_box',
				'title' => 'anastasia::strings.html_box',
				'tpl' => 'anastasia::blocks/htmlbox',
				'params' => 'YTo0OntzOjU6InRpdGxlIjtzOjEzOiJBIGxpdHRsZSBwdXNoIjtzOjQ6InRleHQiO3M6MjQ1OiI8cD5XZSBoYXZlIGFscmVhZHkgY3JlYXRlZCBzb21lIGNvbnRlbnQgZm9yIHlvdSBpbiBvcmRlciB0byBiZSBlYXNpZXIgZm9yIHlvdSB0byB1bmRlcnN0YW5kIGhvdyB0byB3b3JrIHdpdGggQW5hc3Rhc2lhLjxiciAvPldlIGhhdmUgY3JlYXRlZCBhIHBhZ2UsIGEgYmxvZyBwb3N0LCBhIG1lbnUgYW5kIHNvbWUgdGFncy4gWW91IGNhbiBhbHdheXMgcmVhZCBhYm91dCBob3dzIGFuZCB3aHlzIGluIG91ciBkb2NzIHBhZ2VzPC9wPiI7czozOiJ1cmwiO3M6NDI6Imh0dHA6Ly93d3cuYW5hc3Rhc2lhLWFwcC5jb20vZG9jdW1lbnRhdGlvbiI7czo2OiJidXR0b24iO3M6MTk6IlZpc2l0IERvY3VtZW50YXRpb24iO30=',
				'order_weight' => '0',
				'created_at' => '2015-04-19 11:58:29',
				'updated_at' => '2015-04-29 04:31:14',
			),
			3 => 
			array (
				'id' => '4',
				'theme_domain' => 'anastasia',
				'position' => '5',
				'grid' => 'body',
				'layout' => 'default',
				'name' => 'html_box',
				'title' => 'anastasia::strings.html_box',
				'tpl' => 'anastasia::blocks/htmlbox',
				'params' => 'YTo0OntzOjU6InRpdGxlIjtzOjEwOiJUaGFuayB5b3UhIjtzOjQ6InRleHQiO3M6MjUyOiI8cD5UYWtpbmcgdGhlIG9wcG9ydHVuaXR5IHRoYXQgeW91ciBzaXRlIGlzIG5ldyBhbmQgdGhhdCB3ZSByZWFsbHkgbmVlZCB0byBwb3B1bGF0ZSB0aGlzIGJsb2NrIHdpdGggc29tZSBjb250ZW50LCB3ZSB3b3VsZCBsaWtlIHRvIHNheSBhIGJpZyBUSEFOSyBZT1UgZm9yIGdpdmluZyBhIGNoYW5jZSB0byBBbmFzdGFzaWEuPGJyIC8+VGhlIG1vcmUgeW91IHVzZSB0aGlzIHBsYXRmb3JtLCB0aGUgbW9yZSB5b3Ugd2lsbCBsb3ZlIGl0LjwvcD4iO3M6MzoidXJsIjtzOjE6Ii8iO3M6NjoiYnV0dG9uIjtzOjEwOiJUaGFuayB5b3UhIjt9',
				'order_weight' => '0',
				'created_at' => '2015-04-19 12:03:58',
				'updated_at' => '2015-04-29 04:35:07',
			),
			4 => 
			array (
				'id' => '5',
				'theme_domain' => 'anastasia',
				'position' => '1',
				'grid' => 'body',
				'layout' => 'default',
				'name' => 'carousel_block',
				'title' => 'anastasia::strings.carousel',
				'tpl' => 'anastasia::blocks/carousel',
				'params' => 'YToxOntpOjA7YTozOntzOjM6ImltZyI7czoxOiIxIjtzOjM6InVybCI7czo2OiIvYWJvdXQiO3M6NzoiY2FwdGlvbiI7czoxNToiQWJvdXQgQW5hc3Rhc2lhIjt9fQ==',
				'order_weight' => '0',
				'created_at' => '2015-04-20 07:45:28',
				'updated_at' => '2015-04-29 04:22:33',
			),
			5 => 
			array (
				'id' => '6',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page2',
				'name' => 'default_main_content',
				'title' => 'strings.main_content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '0',
				'created_at' => '2015-04-20 08:38:10',
				'updated_at' => '2015-04-20 08:38:20',
			),
			6 => 
			array (
				'id' => '7',
				'theme_domain' => 'anastasia',
				'position' => '3',
				'grid' => 'body',
				'layout' => 'page2',
				'name' => 'default_feed_block',
				'title' => 'strings.rss',
				'tpl' => 'common/blocks/rss',
				'params' => 'YToyOntzOjM6InVybCI7czozNzoiaHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL3NpbXBsZXBpZSI7czozOiJudW0iO2k6NTt9',
				'order_weight' => '0',
				'created_at' => '2015-04-20 08:38:31',
				'updated_at' => '2015-04-20 08:38:31',
			),
			7 => 
			array (
				'id' => '8',
				'theme_domain' => 'anastasia',
				'position' => '4',
				'grid' => 'body',
				'layout' => 'page2',
				'name' => 'default_html_block',
				'title' => 'strings.rich_text',
				'tpl' => 'common/blocks/html',
				'params' => 'YToxOntzOjQ6InRleHQiO3M6MTA6Imh0bWwgYmxvY2siO30=',
				'order_weight' => '0',
				'created_at' => '2015-04-20 08:44:17',
				'updated_at' => '2015-04-20 08:44:17',
			),
			8 => 
			array (
				'id' => '9',
				'theme_domain' => 'anastasia',
				'position' => '5',
				'grid' => 'body',
				'layout' => 'page2',
				'name' => 'default_tagcloud_block',
				'title' => 'strings.tag_cloud',
				'tpl' => 'common/blocks/tagcloud',
				'params' => 'YToxOntpOjA7czoxOiIqIjt9',
				'order_weight' => '0',
				'created_at' => '2015-04-20 08:45:11',
				'updated_at' => '2015-04-20 08:45:11',
			),
			9 => 
			array (
				'id' => '10',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page3',
				'name' => 'default_main_content',
				'title' => 'strings.main_content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '1',
				'created_at' => '2015-04-20 09:00:50',
				'updated_at' => '2015-04-22 14:02:40',
			),
			10 => 
			array (
				'id' => '11',
				'theme_domain' => 'anastasia',
				'position' => 'content',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_main_content',
				'title' => 'strings.main_content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '1',
				'created_at' => '2015-04-20 09:36:15',
				'updated_at' => '2015-04-29 04:45:03',
			),
			11 => 
			array (
				'id' => '12',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'tagpage',
				'name' => 'default_main_content',
				'title' => 'strings.main_content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '1',
				'created_at' => '2015-04-20 11:07:12',
				'updated_at' => '2015-04-22 14:01:03',
			),
			12 => 
			array (
				'id' => '13',
				'theme_domain' => 'anastasia',
				'position' => '1',
				'grid' => 'header',
				'layout' => 'default',
				'name' => 'logo_block',
				'title' => 'Logo',
				'tpl' => 'anastasia::blocks/logo',
				'params' => 'YTowOnt9',
				'order_weight' => '0',
				'created_at' => '2015-04-21 11:58:35',
				'updated_at' => '2015-04-21 11:58:35',
			),
			13 => 
			array (
				'id' => '14',
				'theme_domain' => 'anastasia',
				'position' => 'content',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_tagcloud_block',
				'title' => 'strings.tag_cloud',
				'tpl' => 'common/blocks/tagcloud',
				'params' => 'YToxOntpOjA7czoxOiIqIjt9',
				'order_weight' => '1',
				'created_at' => '2015-04-22 12:22:35',
				'updated_at' => '2015-04-29 04:42:15',
			),
			14 => 
			array (
				'id' => '15',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'posts_index',
				'name' => 'default_main_content',
				'title' => 'strings.main_content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '1',
				'created_at' => '2015-04-22 12:32:40',
				'updated_at' => '2015-04-29 04:44:40',
			),
			15 => 
			array (
				'id' => '16',
				'theme_domain' => 'anastasia',
				'position' => 'content',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'posts_main_content',
				'title' => 'posts::strings.latest_posts',
				'tpl' => 'posts::blocks/latest',
				'params' => 'czoyOiIyMCI7',
				'order_weight' => '1',
				'created_at' => '2015-04-22 12:43:27',
				'updated_at' => '2015-04-29 04:42:42',
			),
			16 => 
			array (
				'id' => '17',
				'theme_domain' => 'anastasia',
				'position' => '1',
				'grid' => 'footer',
				'layout' => 'default',
				'name' => 'menu_select_block',
				'title' => 'Menu',
				'tpl' => 'anastasia::blocks/pills',
				'params' => 'czoxOiI5Ijs=',
				'order_weight' => '0',
				'created_at' => '2015-04-22 13:09:13',
				'updated_at' => '2015-04-29 04:38:27',
			),
			17 => 
			array (
				'id' => '18',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page5',
				'name' => 'default_main_content',
				'title' => 'strings.main_content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '1',
				'created_at' => '2015-04-22 13:38:20',
				'updated_at' => '2015-04-22 13:53:23',
			),
			18 => 
			array (
				'id' => '19',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page5',
				'name' => 'default_static_block',
				'title' => 'Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-22 13:43:42',
				'updated_at' => '2015-04-22 13:53:20',
			),
			19 => 
			array (
				'id' => '20',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'tagpage',
				'name' => 'default_static_block',
				'title' => 'Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-22 14:00:58',
				'updated_at' => '2015-04-22 14:01:09',
			),
			20 => 
			array (
				'id' => '21',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page3',
				'name' => 'default_static_block',
				'title' => 'Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-22 14:02:32',
				'updated_at' => '2015-04-22 14:02:44',
			),
			21 => 
			array (
				'id' => '22',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page7',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-27 13:00:14',
				'updated_at' => '2015-04-27 13:00:22',
			),
			22 => 
			array (
				'id' => '23',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'page7',
				'name' => 'default_main_content',
				'title' => 'Main Content',
				'tpl' => 'common/blocks/maincontent',
				'params' => 'YTowOnt9',
				'order_weight' => '0',
				'created_at' => '2015-04-27 13:00:52',
				'updated_at' => '2015-04-27 13:00:52',
			),
			23 => 
			array (
				'id' => '24',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'default',
				'name' => 'default_title_block',
				'title' => 'Title',
				'tpl' => 'common/blocks/default_title',
				'params' => 'YTozOntzOjU6InRpdGxlIjtzOjI0OiJXZWxjb21lIHRvIEFuYXN0YXNpYSBBUFAiO3M6MTM6ImhlYWRpbmdfbGV2ZWwiO3M6MToiMiI7czo5OiJjbGFzc25hbWUiO3M6MTE6InBhZ2UtaGVhZGVyIjt9',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:23:14',
				'updated_at' => '2015-04-29 04:23:32',
			),
			24 => 
			array (
				'id' => '25',
				'theme_domain' => 'anastasia',
				'position' => '4',
				'grid' => 'footer',
				'layout' => 'default',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/socialicons',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:37:12',
				'updated_at' => '2015-04-29 04:38:33',
			),
			25 => 
			array (
				'id' => '26',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'footer',
				'layout' => 'default',
				'name' => 'default_feed_block',
				'title' => 'RSS File',
				'tpl' => 'common/blocks/rss',
				'params' => 'YToyOntzOjM6InVybCI7czozOToiaHR0cDovL3d3dy5hbmFzdGFzaWEtYXBwLmNvbS9mZWVkcy9ibG9nIjtzOjM6Im51bSI7czoxOiI1Ijt9',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:38:11',
				'updated_at' => '2015-04-29 04:48:09',
			),
			26 => 
			array (
				'id' => '27',
				'theme_domain' => 'anastasia',
				'position' => '3',
				'grid' => 'footer',
				'layout' => 'default',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/mailchimp',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:40:27',
				'updated_at' => '2015-04-29 04:40:45',
			),
			27 => 
			array (
				'id' => '28',
				'theme_domain' => 'anastasia',
				'position' => '3',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_title_block',
				'title' => 'Title',
				'tpl' => 'common/blocks/default_title',
				'params' => 'YTozOntzOjU6InRpdGxlIjtzOjk6IlRhZyBDbG91ZCI7czoxMzoiaGVhZGluZ19sZXZlbCI7czoxOiI0IjtzOjk6ImNsYXNzbmFtZSI7czoxMToicGFnZS1oZWFkZXIiO30=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:42:08',
				'updated_at' => '2015-04-29 04:42:28',
			),
			28 => 
			array (
				'id' => '29',
				'theme_domain' => 'anastasia',
				'position' => '4',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_title_block',
				'title' => 'Title',
				'tpl' => 'common/blocks/default_title',
				'params' => 'YTozOntzOjU6InRpdGxlIjtzOjIwOiJMYXRlc3QgZnJvbSBvdXIgYmxvZyI7czoxMzoiaGVhZGluZ19sZXZlbCI7czoxOiI0IjtzOjk6ImNsYXNzbmFtZSI7czoxMToicGFnZS1oZWFkZXIiO30=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:42:37',
				'updated_at' => '2015-04-29 04:42:53',
			),
			29 => 
			array (
				'id' => '30',
				'theme_domain' => 'anastasia',
				'position' => '5',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_feed_block',
				'title' => 'RSS File',
				'tpl' => 'common/blocks/rss',
				'params' => 'YToyOntzOjM6InVybCI7czozNzoiaHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL3NpbXBsZXBpZSI7czozOiJudW0iO2k6NTt9',
				'order_weight' => '1',
				'created_at' => '2015-04-29 04:43:29',
				'updated_at' => '2015-04-29 04:43:48',
			),
			30 => 
			array (
				'id' => '31',
				'theme_domain' => 'anastasia',
				'position' => '5',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_title_block',
				'title' => 'Title',
				'tpl' => 'common/blocks/default_title',
				'params' => 'YTozOntzOjU6InRpdGxlIjtzOjM6IlJTUyI7czoxMzoiaGVhZGluZ19sZXZlbCI7czoxOiI0IjtzOjk6ImNsYXNzbmFtZSI7czoxMToicGFnZS1oZWFkZXIiO30=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:43:42',
				'updated_at' => '2015-04-29 04:44:05',
			),
			31 => 
			array (
				'id' => '32',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'posts_index',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:44:34',
				'updated_at' => '2015-04-29 04:44:44',
			),
			32 => 
			array (
				'id' => '33',
				'theme_domain' => 'anastasia',
				'position' => '2',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:44:58',
				'updated_at' => '2015-04-29 04:45:06',
			),
			33 => 
			array (
				'id' => '34',
				'theme_domain' => 'anastasia',
				'position' => '3',
				'grid' => 'body',
				'layout' => 'posts_singlepost',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:42:08',
				'updated_at' => '2015-04-29 04:42:28',
			),
			34 => 
			array (
				'id' => '35',
				'theme_domain' => 'anastasia',
				'position' => '3',
				'grid' => 'body',
				'layout' => 'posts_index',
				'name' => 'default_static_block',
				'title' => 'Static Template',
				'tpl' => 'common/blocks/static/breadcrumbs',
				'params' => 'Tjs=',
				'order_weight' => '0',
				'created_at' => '2015-04-29 04:42:08',
				'updated_at' => '2015-04-29 04:42:28',
			),
		));
	}

}
